// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetOverviewData, GetOverviewResponses, GetStatusData, GetStatusResponses, GetAnalyticsData, GetAnalyticsResponses, GetLinesLineIdProfileData, GetLinesLineIdProfileResponses, GetLinesLineIdProfileErrors, GetIssuesIssueIdData, GetIssuesIssueIdResponses, GetIssuesIssueIdErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Overview endpoint
 */
export const getOverview = <ThrowOnError extends boolean = false>(options?: Options<GetOverviewData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetOverviewResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/overview',
        ...options
    });
};

/**
 * Get an overview of the current status of the network.
 */
export const getStatus = <ThrowOnError extends boolean = false>(options?: Options<GetStatusData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetStatusResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/status',
        ...options
    });
};

/**
 * Get an overview of the analytics data.
 */
export const getAnalytics = <ThrowOnError extends boolean = false>(options?: Options<GetAnalyticsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAnalyticsResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/analytics',
        ...options
    });
};

/**
 * Get the profile of a line
 */
export const getLinesLineIdProfile = <ThrowOnError extends boolean = false>(options: Options<GetLinesLineIdProfileData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetLinesLineIdProfileResponses, GetLinesLineIdProfileErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/lines/{lineId}/profile',
        ...options
    });
};

/**
 * Get issue details
 */
export const getIssuesIssueId = <ThrowOnError extends boolean = false>(options: Options<GetIssuesIssueIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetIssuesIssueIdResponses, GetIssuesIssueIdErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/issues/{issueId}',
        ...options
    });
};