// This file is auto-generated by @hey-api/openapi-ts

/**
 * Represents a line in the network.
 */
export type Line = {
    id: string;
    title: string;
    titleTranslations: {
        [key: string]: string;
    };
    color: string;
    startedAt: string | null;
    operatingHours: {
        weekdays: {
            start: string;
            end: string;
        };
        weekends: {
            start: string;
            end: string;
        };
    };
};

/**
 * Describes the membership of a station in a specific line, including its code, start and end dates, and structure type.
 */
export type StationLineMembership = {
    /**
     * ID of the line to which the station belongs
     */
    lineId: string;
    /**
     * ID of the branch
     */
    branchId: string;
    /**
     * Code of the station
     */
    code: string;
    /**
     * Date when the station was added to the line
     */
    startedAt: string;
    /**
     * Date when the station was removed from the line, if applicable
     */
    endedAt?: string;
    /**
     * Structure type of the station
     */
    structureType: 'elevated' | 'underground' | 'at_grade' | 'in_building';
    /**
     * Order of the station in the branch sequence
     */
    sequenceOrder: number;
};

/**
 * A station in the network, identified by its unique ID.
 */
export type Station = {
    id: string;
    name: string;
    nameTranslations: {
        [key: string]: string;
    };
    town: string;
    townTranslations: {
        [key: string]: string;
    };
    geo: {
        /**
         * Latitude of the station
         */
        latitude: number;
        /**
         * Longitude of the station
         */
        longitude: number;
    };
    /**
     * List of line memberships for the station
     */
    memberships: Array<StationLineMembership>;
};

/**
 * A branch of a line affected by the issue, including the stations impacted.
 */
export type IssueAffectedBranch = {
    lineId: string;
    branchId: string;
    stationIds: Array<string>;
};

/**
 * The status of the issue interval, indicating whether it is currently ongoing, has ended, or is upcoming.
 */
export type IssueIntervalStatus = 'ongoing' | 'ended' | 'future';

export type IssueInterval = {
    startAt: string;
    endAt: string | null;
    status: IssueIntervalStatus;
};

export type Issue = {
    id: string;
    title: string;
    titleTranslations: {
        [key: string]: string;
    };
    type: 'disruption' | 'maintenance' | 'infra';
    durationSeconds: number;
    /**
     * IDs of lines affected by the issue.
     */
    lineIds: Array<string>;
    /**
     * Branches of lines affected by the issue, including stations impacted.
     */
    branchesAffected: Array<IssueAffectedBranch>;
    intervals: Array<IssueInterval>;
};

/**
 * Included entities that are referenced in the response.
 */
export type IncludedEntities = {
    lines: {
        [key: string]: Line;
    };
    stations: {
        [key: string]: Station;
    };
    issues: {
        [key: string]: Issue;
    };
};

/**
 * Status of the line summary, indicating the current operational state.
 */
export type LineSummaryStatus = 'future_service' | 'closed_for_day' | 'ongoing_disruption' | 'ongoing_maintenance' | 'ongoing_infra' | 'normal';

/**
 * Basic summary of a line, including its status and ongoing issues.
 */
export type LineSummaryBasic = {
    lineId: string;
    status: LineSummaryStatus;
    /**
     * List of ongoing issue IDs affecting this line.
     */
    issueIdsOngoing: Array<string>;
};

/**
 * Overview of the entire system, including ongoing issues and line summaries.
 */
export type SystemOverview = {
    /**
     * List of ongoing issues in the network.
     */
    issueOngoingIds: Array<string>;
    lineSummaries: Array<LineSummaryBasic>;
};

/**
 * Details of issues for a specific date and issue type.
 */
export type LineSummaryDateRecordIssueTypeEntry = {
    totalDurationSeconds: number;
    /**
     * List of issue IDs for this issue type on this date.
     */
    issueIds: Array<string>;
};

/**
 * Type of day for the breakdown.
 */
export type LineSummaryDayType = 'weekday' | 'weekend' | 'public_holiday';

/**
 * Breakdown of issues by date for a line summary.
 */
export type LineSummaryDateRecord = {
    breakdownByIssueTypes: {
        [key: string]: LineSummaryDateRecordIssueTypeEntry;
    };
    dayType: LineSummaryDayType;
};

/**
 * Summary of the status and issues for a specific line.
 */
export type LineSummary = {
    lineId: string;
    status: LineSummaryStatus;
    /**
     * Total duration in seconds for each issue type affecting this line.
     */
    durationSecondsByIssueType: {
        [key: string]: number;
    };
    /**
     * Total duration in seconds for all issues affecting this line.
     */
    durationSecondsTotalForIssues: number;
    /**
     * Breakdown of issues by date for this line.
     */
    breakdownByDates: {
        [key: string]: LineSummaryDateRecord;
    };
    uptimeRatio: number | null;
    totalServiceSeconds: number | null;
    totalDowntimeSeconds: number | null;
    downtimeBreakdown: Array<{
        type: 'disruption' | 'maintenance' | 'infra';
        downtimeSeconds: number;
    }> | null;
};

/**
 * Overall status of the transit system, including line summaries and ongoing issues.
 */
export type SystemStatus = {
    lineSummaries: Array<LineSummary>;
    /**
     * List of ongoing issues in the network.
     */
    issueOngoingIds: Array<string>;
};

/**
 * An entry in a chart, representing a data point with a name and associated payload.
 */
export type ChartEntry = {
    name: string;
    payload: {
        [key: string]: number;
    };
};

export type Granularity = 'day' | 'month' | 'year';

export type TimeScale = {
    granularity: Granularity;
    count: number;
};

/**
 * A chart that includes time scale information for both display and data granularity.
 */
export type TimeScaleChart = {
    title: string;
    data: Array<ChartEntry>;
    displayTimeScale?: TimeScale;
    dataTimeScale: TimeScale;
    /**
     * Cumulative data entries for the chart.
     */
    dataCumulative: Array<ChartEntry>;
};

/**
 * A chart containing a title and a list of data entries.
 */
export type Chart = {
    title: string;
    data: Array<ChartEntry>;
};

/**
 * System-level analytics, including various graphs and breakdowns.
 */
export type SystemAnalytics = {
    timeScaleChartsIssueCount: Array<TimeScaleChart>;
    timeScaleChartsIssueDuration: Array<TimeScaleChart>;
    chartTotalIssueCountByLine: Chart;
    chartTotalIssueCountByStation: Chart;
    issueIdsDisruptionLongest: Array<string>;
};

/**
 * A branch of a line, consisting of multiple stations.
 */
export type LineBranch = {
    id: string;
    title: string;
    titleTranslations: {
        [key: string]: string;
    };
    startedAt: string | null;
    endedAt: string | null;
    /**
     * List of station IDs in this branch, ordered by sequence.
     */
    stationIds: Array<string>;
};

/**
 * Profile of a line, including its details and status.
 */
export type LineProfile = {
    lineId: string;
    lineSummary: LineSummary;
    branches: Array<LineBranch>;
    /**
     * The next scheduled maintenance for the line, if any.
     */
    issueIdNextMaintenance: string | null;
    /**
     * List of recent issues affecting the line.
     */
    issueIdsRecent: Array<string>;
    issueCountByType: {
        [key: string]: number;
    };
    timeScaleGraphsIssueCount: Array<TimeScaleChart>;
    timeScaleGraphsUptimeRatios: Array<TimeScaleChart>;
    /**
     * List of station IDs that are interchanges on this line.
     */
    stationIdsInterchanges: Array<string>;
};

/**
 * A textual update for an issue
 */
export type IssueUpdate = {
    type: string;
    text: string;
    sourceUrl: string | null;
    createdAt: string;
};

export type GetOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/overview';
};

export type GetOverviewResponses = {
    /**
     * Successful overview response
     */
    200: {
        success: true;
        included: IncludedEntities;
        data: SystemOverview;
    };
};

export type GetOverviewResponse = GetOverviewResponses[keyof GetOverviewResponses];

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: {
        days?: number;
    };
    url: '/status';
};

export type GetStatusResponses = {
    /**
     * Successful Response
     */
    200: {
        success: true;
        included: IncludedEntities;
        data: SystemStatus;
    };
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type GetAnalyticsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/analytics';
};

export type GetAnalyticsResponses = {
    /**
     * Successful overview response
     */
    200: {
        success: true;
        included: IncludedEntities;
        data: SystemAnalytics;
    };
};

export type GetAnalyticsResponse = GetAnalyticsResponses[keyof GetAnalyticsResponses];

export type GetLinesLineIdProfileData = {
    body?: never;
    path: {
        lineId: string;
    };
    query?: {
        days?: number;
    };
    url: '/lines/{lineId}/profile';
};

export type GetLinesLineIdProfileErrors = {
    /**
     * Line not found
     */
    404: {
        success?: boolean;
        error?: string;
    };
};

export type GetLinesLineIdProfileError = GetLinesLineIdProfileErrors[keyof GetLinesLineIdProfileErrors];

export type GetLinesLineIdProfileResponses = {
    /**
     * Successful line profile response
     */
    200: {
        success: true;
        included: IncludedEntities;
        data: LineProfile;
    };
};

export type GetLinesLineIdProfileResponse = GetLinesLineIdProfileResponses[keyof GetLinesLineIdProfileResponses];

export type GetIssuesIssueIdData = {
    body?: never;
    path: {
        issueId: string;
    };
    query?: never;
    url: '/issues/{issueId}';
};

export type GetIssuesIssueIdErrors = {
    /**
     * Issue not found
     */
    404: {
        success?: boolean;
        error?: string;
    };
};

export type GetIssuesIssueIdError = GetIssuesIssueIdErrors[keyof GetIssuesIssueIdErrors];

export type GetIssuesIssueIdResponses = {
    /**
     * Successful response
     */
    200: {
        success: true;
        included: IncludedEntities;
        data: {
            id: string;
            updates: Array<IssueUpdate>;
        };
    };
};

export type GetIssuesIssueIdResponse = GetIssuesIssueIdResponses[keyof GetIssuesIssueIdResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:4000' | (string & {});
};