/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as IndexDotmdRouteImport } from './routes/index[.]md'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as Char123LangChar125RouteRouteImport } from './routes/{-$lang}/route'
import { Route as Char123LangChar125IndexRouteImport } from './routes/{-$lang}/index'
import { Route as Char123LangChar125SitemapDotxmlRouteImport } from './routes/{-$lang}/sitemap[.]xml'
import { Route as ApiSentryAnonymousUserRouteImport } from './routes/api.sentry-anonymous-user'
import { Route as ApiReportsRouteImport } from './routes/api.reports'
import { Route as ApiIssuesDayRouteImport } from './routes/api.issues-day'
import { Route as Char123LangChar125TownsIndexRouteImport } from './routes/{-$lang}/towns/index'
import { Route as Char123LangChar125SystemMapIndexRouteImport } from './routes/{-$lang}/system-map/index'
import { Route as Char123LangChar125StatisticsIndexRouteImport } from './routes/{-$lang}/statistics/index'
import { Route as Char123LangChar125StationsIndexRouteImport } from './routes/{-$lang}/stations/index'
import { Route as Char123LangChar125ReportIndexRouteImport } from './routes/{-$lang}/report/index'
import { Route as Char123LangChar125LinesIndexRouteImport } from './routes/{-$lang}/lines/index'
import { Route as Char123LangChar125HistoryIndexRouteImport } from './routes/{-$lang}/history/index'
import { Route as Char123LangChar125AboutIndexRouteImport } from './routes/{-$lang}/about/index'
import { Route as StationsStationIdIndexDotmdRouteImport } from './routes/stations/$stationId/index[.]md'
import { Route as OperatorsOperatorIdIndexDotmdRouteImport } from './routes/operators/$operatorId/index[.]md'
import { Route as LinesLineIdIndexDotmdRouteImport } from './routes/lines/$lineId/index[.]md'
import { Route as IssuesIssueIdIndexDotmdRouteImport } from './routes/issues/$issueId/index[.]md'
import { Route as ApiPhSplatRouteImport } from './routes/api.ph.$'
import { Route as Char123LangChar125TownsTownIdIndexRouteImport } from './routes/{-$lang}/towns/$townId/index'
import { Route as Char123LangChar125StatusLineIdIndexRouteImport } from './routes/{-$lang}/status/$lineId/index'
import { Route as Char123LangChar125StationsStationIdIndexRouteImport } from './routes/{-$lang}/stations/$stationId/index'
import { Route as Char123LangChar125OperatorsOperatorIdIndexRouteImport } from './routes/{-$lang}/operators/$operatorId/index'
import { Route as Char123LangChar125LinesLineIdIndexRouteImport } from './routes/{-$lang}/lines/$lineId/index'
import { Route as Char123LangChar125IssuesIssueIdIndexRouteImport } from './routes/{-$lang}/issues/$issueId/index'
import { Route as Char123LangChar125HistoryYearIndexRouteImport } from './routes/{-$lang}/history/$year/index'
import { Route as InternalApiWorkflowsWorkflowNameRouteImport } from './routes/internal.api.workflows.$workflowName'
import { Route as InternalApiTasksPullRouteImport } from './routes/internal.api.tasks.pull'
import { Route as InternalApiTasksPublicHolidaysRouteImport } from './routes/internal.api.tasks.public-holidays'
import { Route as InternalApiTasksFactsRouteImport } from './routes/internal.api.tasks.facts'
import { Route as InternalApiTasksCrowdReportDispatchRouteImport } from './routes/internal.api.tasks.crowd-report-dispatch'
import { Route as Char123LangChar125HistoryPagePageNumIndexRouteImport } from './routes/{-$lang}/history/page/$pageNum/index'
import { Route as Char123LangChar125HistoryYearMonthIndexRouteImport } from './routes/{-$lang}/history/$year/$month/index'
import { Route as Char123LangChar125CommunityReportsKindSourceIdIndexRouteImport } from './routes/{-$lang}/community-reports/$kind/$sourceId/index'

const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexDotmdRoute = IndexDotmdRouteImport.update({
  id: '/index.md',
  path: '/index.md',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125RouteRoute = Char123LangChar125RouteRouteImport.update({
  id: '/{-$lang}',
  path: '/{-$lang}',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125IndexRoute = Char123LangChar125IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Char123LangChar125RouteRoute,
} as any)
const Char123LangChar125SitemapDotxmlRoute =
  Char123LangChar125SitemapDotxmlRouteImport.update({
    id: '/sitemap.xml',
    path: '/sitemap.xml',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const ApiSentryAnonymousUserRoute = ApiSentryAnonymousUserRouteImport.update({
  id: '/api/sentry-anonymous-user',
  path: '/api/sentry-anonymous-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsRoute = ApiReportsRouteImport.update({
  id: '/api/reports',
  path: '/api/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIssuesDayRoute = ApiIssuesDayRouteImport.update({
  id: '/api/issues-day',
  path: '/api/issues-day',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125TownsIndexRoute =
  Char123LangChar125TownsIndexRouteImport.update({
    id: '/towns/',
    path: '/towns/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125SystemMapIndexRoute =
  Char123LangChar125SystemMapIndexRouteImport.update({
    id: '/system-map/',
    path: '/system-map/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125StatisticsIndexRoute =
  Char123LangChar125StatisticsIndexRouteImport.update({
    id: '/statistics/',
    path: '/statistics/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125StationsIndexRoute =
  Char123LangChar125StationsIndexRouteImport.update({
    id: '/stations/',
    path: '/stations/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125ReportIndexRoute =
  Char123LangChar125ReportIndexRouteImport.update({
    id: '/report/',
    path: '/report/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125LinesIndexRoute =
  Char123LangChar125LinesIndexRouteImport.update({
    id: '/lines/',
    path: '/lines/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125HistoryIndexRoute =
  Char123LangChar125HistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125AboutIndexRoute =
  Char123LangChar125AboutIndexRouteImport.update({
    id: '/about/',
    path: '/about/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const StationsStationIdIndexDotmdRoute =
  StationsStationIdIndexDotmdRouteImport.update({
    id: '/stations/$stationId/index.md',
    path: '/stations/$stationId/index.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperatorsOperatorIdIndexDotmdRoute =
  OperatorsOperatorIdIndexDotmdRouteImport.update({
    id: '/operators/$operatorId/index.md',
    path: '/operators/$operatorId/index.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const LinesLineIdIndexDotmdRoute = LinesLineIdIndexDotmdRouteImport.update({
  id: '/lines/$lineId/index.md',
  path: '/lines/$lineId/index.md',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIssueIdIndexDotmdRoute = IssuesIssueIdIndexDotmdRouteImport.update({
  id: '/issues/$issueId/index.md',
  path: '/issues/$issueId/index.md',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhSplatRoute = ApiPhSplatRouteImport.update({
  id: '/api/ph/$',
  path: '/api/ph/$',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125TownsTownIdIndexRoute =
  Char123LangChar125TownsTownIdIndexRouteImport.update({
    id: '/towns/$townId/',
    path: '/towns/$townId/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125StatusLineIdIndexRoute =
  Char123LangChar125StatusLineIdIndexRouteImport.update({
    id: '/status/$lineId/',
    path: '/status/$lineId/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125StationsStationIdIndexRoute =
  Char123LangChar125StationsStationIdIndexRouteImport.update({
    id: '/stations/$stationId/',
    path: '/stations/$stationId/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125OperatorsOperatorIdIndexRoute =
  Char123LangChar125OperatorsOperatorIdIndexRouteImport.update({
    id: '/operators/$operatorId/',
    path: '/operators/$operatorId/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125LinesLineIdIndexRoute =
  Char123LangChar125LinesLineIdIndexRouteImport.update({
    id: '/lines/$lineId/',
    path: '/lines/$lineId/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125IssuesIssueIdIndexRoute =
  Char123LangChar125IssuesIssueIdIndexRouteImport.update({
    id: '/issues/$issueId/',
    path: '/issues/$issueId/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125HistoryYearIndexRoute =
  Char123LangChar125HistoryYearIndexRouteImport.update({
    id: '/history/$year/',
    path: '/history/$year/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const InternalApiWorkflowsWorkflowNameRoute =
  InternalApiWorkflowsWorkflowNameRouteImport.update({
    id: '/internal/api/workflows/$workflowName',
    path: '/internal/api/workflows/$workflowName',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalApiTasksPullRoute = InternalApiTasksPullRouteImport.update({
  id: '/internal/api/tasks/pull',
  path: '/internal/api/tasks/pull',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalApiTasksPublicHolidaysRoute =
  InternalApiTasksPublicHolidaysRouteImport.update({
    id: '/internal/api/tasks/public-holidays',
    path: '/internal/api/tasks/public-holidays',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalApiTasksFactsRoute = InternalApiTasksFactsRouteImport.update({
  id: '/internal/api/tasks/facts',
  path: '/internal/api/tasks/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalApiTasksCrowdReportDispatchRoute =
  InternalApiTasksCrowdReportDispatchRouteImport.update({
    id: '/internal/api/tasks/crowd-report-dispatch',
    path: '/internal/api/tasks/crowd-report-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125HistoryPagePageNumIndexRoute =
  Char123LangChar125HistoryPagePageNumIndexRouteImport.update({
    id: '/history/page/$pageNum/',
    path: '/history/page/$pageNum/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125HistoryYearMonthIndexRoute =
  Char123LangChar125HistoryYearMonthIndexRouteImport.update({
    id: '/history/$year/$month/',
    path: '/history/$year/$month/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125CommunityReportsKindSourceIdIndexRoute =
  Char123LangChar125CommunityReportsKindSourceIdIndexRouteImport.update({
    id: '/community-reports/$kind/$sourceId/',
    path: '/community-reports/$kind/$sourceId/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$lang}': typeof Char123LangChar125RouteRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/index.md': typeof IndexDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/issues-day': typeof ApiIssuesDayRoute
  '/api/reports': typeof ApiReportsRoute
  '/api/sentry-anonymous-user': typeof ApiSentryAnonymousUserRoute
  '/{-$lang}/sitemap.xml': typeof Char123LangChar125SitemapDotxmlRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/api/ph/$': typeof ApiPhSplatRoute
  '/issues/$issueId/index.md': typeof IssuesIssueIdIndexDotmdRoute
  '/lines/$lineId/index.md': typeof LinesLineIdIndexDotmdRoute
  '/operators/$operatorId/index.md': typeof OperatorsOperatorIdIndexDotmdRoute
  '/stations/$stationId/index.md': typeof StationsStationIdIndexDotmdRoute
  '/{-$lang}/about/': typeof Char123LangChar125AboutIndexRoute
  '/{-$lang}/history/': typeof Char123LangChar125HistoryIndexRoute
  '/{-$lang}/lines/': typeof Char123LangChar125LinesIndexRoute
  '/{-$lang}/report/': typeof Char123LangChar125ReportIndexRoute
  '/{-$lang}/stations/': typeof Char123LangChar125StationsIndexRoute
  '/{-$lang}/statistics/': typeof Char123LangChar125StatisticsIndexRoute
  '/{-$lang}/system-map/': typeof Char123LangChar125SystemMapIndexRoute
  '/{-$lang}/towns/': typeof Char123LangChar125TownsIndexRoute
  '/internal/api/tasks/crowd-report-dispatch': typeof InternalApiTasksCrowdReportDispatchRoute
  '/internal/api/tasks/facts': typeof InternalApiTasksFactsRoute
  '/internal/api/tasks/public-holidays': typeof InternalApiTasksPublicHolidaysRoute
  '/internal/api/tasks/pull': typeof InternalApiTasksPullRoute
  '/internal/api/workflows/$workflowName': typeof InternalApiWorkflowsWorkflowNameRoute
  '/{-$lang}/history/$year/': typeof Char123LangChar125HistoryYearIndexRoute
  '/{-$lang}/issues/$issueId/': typeof Char123LangChar125IssuesIssueIdIndexRoute
  '/{-$lang}/lines/$lineId/': typeof Char123LangChar125LinesLineIdIndexRoute
  '/{-$lang}/operators/$operatorId/': typeof Char123LangChar125OperatorsOperatorIdIndexRoute
  '/{-$lang}/stations/$stationId/': typeof Char123LangChar125StationsStationIdIndexRoute
  '/{-$lang}/status/$lineId/': typeof Char123LangChar125StatusLineIdIndexRoute
  '/{-$lang}/towns/$townId/': typeof Char123LangChar125TownsTownIdIndexRoute
  '/{-$lang}/community-reports/$kind/$sourceId/': typeof Char123LangChar125CommunityReportsKindSourceIdIndexRoute
  '/{-$lang}/history/$year/$month/': typeof Char123LangChar125HistoryYearMonthIndexRoute
  '/{-$lang}/history/page/$pageNum/': typeof Char123LangChar125HistoryPagePageNumIndexRoute
}
export interface FileRoutesByTo {
  '/healthz': typeof HealthzRoute
  '/index.md': typeof IndexDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/issues-day': typeof ApiIssuesDayRoute
  '/api/reports': typeof ApiReportsRoute
  '/api/sentry-anonymous-user': typeof ApiSentryAnonymousUserRoute
  '/{-$lang}/sitemap.xml': typeof Char123LangChar125SitemapDotxmlRoute
  '/{-$lang}': typeof Char123LangChar125IndexRoute
  '/api/ph/$': typeof ApiPhSplatRoute
  '/issues/$issueId/index.md': typeof IssuesIssueIdIndexDotmdRoute
  '/lines/$lineId/index.md': typeof LinesLineIdIndexDotmdRoute
  '/operators/$operatorId/index.md': typeof OperatorsOperatorIdIndexDotmdRoute
  '/stations/$stationId/index.md': typeof StationsStationIdIndexDotmdRoute
  '/{-$lang}/about': typeof Char123LangChar125AboutIndexRoute
  '/{-$lang}/history': typeof Char123LangChar125HistoryIndexRoute
  '/{-$lang}/lines': typeof Char123LangChar125LinesIndexRoute
  '/{-$lang}/report': typeof Char123LangChar125ReportIndexRoute
  '/{-$lang}/stations': typeof Char123LangChar125StationsIndexRoute
  '/{-$lang}/statistics': typeof Char123LangChar125StatisticsIndexRoute
  '/{-$lang}/system-map': typeof Char123LangChar125SystemMapIndexRoute
  '/{-$lang}/towns': typeof Char123LangChar125TownsIndexRoute
  '/internal/api/tasks/crowd-report-dispatch': typeof InternalApiTasksCrowdReportDispatchRoute
  '/internal/api/tasks/facts': typeof InternalApiTasksFactsRoute
  '/internal/api/tasks/public-holidays': typeof InternalApiTasksPublicHolidaysRoute
  '/internal/api/tasks/pull': typeof InternalApiTasksPullRoute
  '/internal/api/workflows/$workflowName': typeof InternalApiWorkflowsWorkflowNameRoute
  '/{-$lang}/history/$year': typeof Char123LangChar125HistoryYearIndexRoute
  '/{-$lang}/issues/$issueId': typeof Char123LangChar125IssuesIssueIdIndexRoute
  '/{-$lang}/lines/$lineId': typeof Char123LangChar125LinesLineIdIndexRoute
  '/{-$lang}/operators/$operatorId': typeof Char123LangChar125OperatorsOperatorIdIndexRoute
  '/{-$lang}/stations/$stationId': typeof Char123LangChar125StationsStationIdIndexRoute
  '/{-$lang}/status/$lineId': typeof Char123LangChar125StatusLineIdIndexRoute
  '/{-$lang}/towns/$townId': typeof Char123LangChar125TownsTownIdIndexRoute
  '/{-$lang}/community-reports/$kind/$sourceId': typeof Char123LangChar125CommunityReportsKindSourceIdIndexRoute
  '/{-$lang}/history/$year/$month': typeof Char123LangChar125HistoryYearMonthIndexRoute
  '/{-$lang}/history/page/$pageNum': typeof Char123LangChar125HistoryPagePageNumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$lang}': typeof Char123LangChar125RouteRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/index.md': typeof IndexDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/issues-day': typeof ApiIssuesDayRoute
  '/api/reports': typeof ApiReportsRoute
  '/api/sentry-anonymous-user': typeof ApiSentryAnonymousUserRoute
  '/{-$lang}/sitemap.xml': typeof Char123LangChar125SitemapDotxmlRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/api/ph/$': typeof ApiPhSplatRoute
  '/issues/$issueId/index.md': typeof IssuesIssueIdIndexDotmdRoute
  '/lines/$lineId/index.md': typeof LinesLineIdIndexDotmdRoute
  '/operators/$operatorId/index.md': typeof OperatorsOperatorIdIndexDotmdRoute
  '/stations/$stationId/index.md': typeof StationsStationIdIndexDotmdRoute
  '/{-$lang}/about/': typeof Char123LangChar125AboutIndexRoute
  '/{-$lang}/history/': typeof Char123LangChar125HistoryIndexRoute
  '/{-$lang}/lines/': typeof Char123LangChar125LinesIndexRoute
  '/{-$lang}/report/': typeof Char123LangChar125ReportIndexRoute
  '/{-$lang}/stations/': typeof Char123LangChar125StationsIndexRoute
  '/{-$lang}/statistics/': typeof Char123LangChar125StatisticsIndexRoute
  '/{-$lang}/system-map/': typeof Char123LangChar125SystemMapIndexRoute
  '/{-$lang}/towns/': typeof Char123LangChar125TownsIndexRoute
  '/internal/api/tasks/crowd-report-dispatch': typeof InternalApiTasksCrowdReportDispatchRoute
  '/internal/api/tasks/facts': typeof InternalApiTasksFactsRoute
  '/internal/api/tasks/public-holidays': typeof InternalApiTasksPublicHolidaysRoute
  '/internal/api/tasks/pull': typeof InternalApiTasksPullRoute
  '/internal/api/workflows/$workflowName': typeof InternalApiWorkflowsWorkflowNameRoute
  '/{-$lang}/history/$year/': typeof Char123LangChar125HistoryYearIndexRoute
  '/{-$lang}/issues/$issueId/': typeof Char123LangChar125IssuesIssueIdIndexRoute
  '/{-$lang}/lines/$lineId/': typeof Char123LangChar125LinesLineIdIndexRoute
  '/{-$lang}/operators/$operatorId/': typeof Char123LangChar125OperatorsOperatorIdIndexRoute
  '/{-$lang}/stations/$stationId/': typeof Char123LangChar125StationsStationIdIndexRoute
  '/{-$lang}/status/$lineId/': typeof Char123LangChar125StatusLineIdIndexRoute
  '/{-$lang}/towns/$townId/': typeof Char123LangChar125TownsTownIdIndexRoute
  '/{-$lang}/community-reports/$kind/$sourceId/': typeof Char123LangChar125CommunityReportsKindSourceIdIndexRoute
  '/{-$lang}/history/$year/$month/': typeof Char123LangChar125HistoryYearMonthIndexRoute
  '/{-$lang}/history/page/$pageNum/': typeof Char123LangChar125HistoryPagePageNumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$lang}'
    | '/healthz'
    | '/index.md'
    | '/llms.txt'
    | '/api/issues-day'
    | '/api/reports'
    | '/api/sentry-anonymous-user'
    | '/{-$lang}/sitemap.xml'
    | '/{-$lang}/'
    | '/api/ph/$'
    | '/issues/$issueId/index.md'
    | '/lines/$lineId/index.md'
    | '/operators/$operatorId/index.md'
    | '/stations/$stationId/index.md'
    | '/{-$lang}/about/'
    | '/{-$lang}/history/'
    | '/{-$lang}/lines/'
    | '/{-$lang}/report/'
    | '/{-$lang}/stations/'
    | '/{-$lang}/statistics/'
    | '/{-$lang}/system-map/'
    | '/{-$lang}/towns/'
    | '/internal/api/tasks/crowd-report-dispatch'
    | '/internal/api/tasks/facts'
    | '/internal/api/tasks/public-holidays'
    | '/internal/api/tasks/pull'
    | '/internal/api/workflows/$workflowName'
    | '/{-$lang}/history/$year/'
    | '/{-$lang}/issues/$issueId/'
    | '/{-$lang}/lines/$lineId/'
    | '/{-$lang}/operators/$operatorId/'
    | '/{-$lang}/stations/$stationId/'
    | '/{-$lang}/status/$lineId/'
    | '/{-$lang}/towns/$townId/'
    | '/{-$lang}/community-reports/$kind/$sourceId/'
    | '/{-$lang}/history/$year/$month/'
    | '/{-$lang}/history/page/$pageNum/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/healthz'
    | '/index.md'
    | '/llms.txt'
    | '/api/issues-day'
    | '/api/reports'
    | '/api/sentry-anonymous-user'
    | '/{-$lang}/sitemap.xml'
    | '/{-$lang}'
    | '/api/ph/$'
    | '/issues/$issueId/index.md'
    | '/lines/$lineId/index.md'
    | '/operators/$operatorId/index.md'
    | '/stations/$stationId/index.md'
    | '/{-$lang}/about'
    | '/{-$lang}/history'
    | '/{-$lang}/lines'
    | '/{-$lang}/report'
    | '/{-$lang}/stations'
    | '/{-$lang}/statistics'
    | '/{-$lang}/system-map'
    | '/{-$lang}/towns'
    | '/internal/api/tasks/crowd-report-dispatch'
    | '/internal/api/tasks/facts'
    | '/internal/api/tasks/public-holidays'
    | '/internal/api/tasks/pull'
    | '/internal/api/workflows/$workflowName'
    | '/{-$lang}/history/$year'
    | '/{-$lang}/issues/$issueId'
    | '/{-$lang}/lines/$lineId'
    | '/{-$lang}/operators/$operatorId'
    | '/{-$lang}/stations/$stationId'
    | '/{-$lang}/status/$lineId'
    | '/{-$lang}/towns/$townId'
    | '/{-$lang}/community-reports/$kind/$sourceId'
    | '/{-$lang}/history/$year/$month'
    | '/{-$lang}/history/page/$pageNum'
  id:
    | '__root__'
    | '/{-$lang}'
    | '/healthz'
    | '/index.md'
    | '/llms.txt'
    | '/api/issues-day'
    | '/api/reports'
    | '/api/sentry-anonymous-user'
    | '/{-$lang}/sitemap.xml'
    | '/{-$lang}/'
    | '/api/ph/$'
    | '/issues/$issueId/index.md'
    | '/lines/$lineId/index.md'
    | '/operators/$operatorId/index.md'
    | '/stations/$stationId/index.md'
    | '/{-$lang}/about/'
    | '/{-$lang}/history/'
    | '/{-$lang}/lines/'
    | '/{-$lang}/report/'
    | '/{-$lang}/stations/'
    | '/{-$lang}/statistics/'
    | '/{-$lang}/system-map/'
    | '/{-$lang}/towns/'
    | '/internal/api/tasks/crowd-report-dispatch'
    | '/internal/api/tasks/facts'
    | '/internal/api/tasks/public-holidays'
    | '/internal/api/tasks/pull'
    | '/internal/api/workflows/$workflowName'
    | '/{-$lang}/history/$year/'
    | '/{-$lang}/issues/$issueId/'
    | '/{-$lang}/lines/$lineId/'
    | '/{-$lang}/operators/$operatorId/'
    | '/{-$lang}/stations/$stationId/'
    | '/{-$lang}/status/$lineId/'
    | '/{-$lang}/towns/$townId/'
    | '/{-$lang}/community-reports/$kind/$sourceId/'
    | '/{-$lang}/history/$year/$month/'
    | '/{-$lang}/history/page/$pageNum/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LangChar125RouteRoute: typeof Char123LangChar125RouteRouteWithChildren
  HealthzRoute: typeof HealthzRoute
  IndexDotmdRoute: typeof IndexDotmdRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ApiIssuesDayRoute: typeof ApiIssuesDayRoute
  ApiReportsRoute: typeof ApiReportsRoute
  ApiSentryAnonymousUserRoute: typeof ApiSentryAnonymousUserRoute
  ApiPhSplatRoute: typeof ApiPhSplatRoute
  IssuesIssueIdIndexDotmdRoute: typeof IssuesIssueIdIndexDotmdRoute
  LinesLineIdIndexDotmdRoute: typeof LinesLineIdIndexDotmdRoute
  OperatorsOperatorIdIndexDotmdRoute: typeof OperatorsOperatorIdIndexDotmdRoute
  StationsStationIdIndexDotmdRoute: typeof StationsStationIdIndexDotmdRoute
  InternalApiTasksCrowdReportDispatchRoute: typeof InternalApiTasksCrowdReportDispatchRoute
  InternalApiTasksFactsRoute: typeof InternalApiTasksFactsRoute
  InternalApiTasksPublicHolidaysRoute: typeof InternalApiTasksPublicHolidaysRoute
  InternalApiTasksPullRoute: typeof InternalApiTasksPullRoute
  InternalApiWorkflowsWorkflowNameRoute: typeof InternalApiWorkflowsWorkflowNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index.md': {
      id: '/index.md'
      path: '/index.md'
      fullPath: '/index.md'
      preLoaderRoute: typeof IndexDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}': {
      id: '/{-$lang}'
      path: '/{-$lang}'
      fullPath: '/{-$lang}'
      preLoaderRoute: typeof Char123LangChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/': {
      id: '/{-$lang}/'
      path: '/'
      fullPath: '/{-$lang}/'
      preLoaderRoute: typeof Char123LangChar125IndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/sitemap.xml': {
      id: '/{-$lang}/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/{-$lang}/sitemap.xml'
      preLoaderRoute: typeof Char123LangChar125SitemapDotxmlRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/api/sentry-anonymous-user': {
      id: '/api/sentry-anonymous-user'
      path: '/api/sentry-anonymous-user'
      fullPath: '/api/sentry-anonymous-user'
      preLoaderRoute: typeof ApiSentryAnonymousUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports': {
      id: '/api/reports'
      path: '/api/reports'
      fullPath: '/api/reports'
      preLoaderRoute: typeof ApiReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/issues-day': {
      id: '/api/issues-day'
      path: '/api/issues-day'
      fullPath: '/api/issues-day'
      preLoaderRoute: typeof ApiIssuesDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/towns/': {
      id: '/{-$lang}/towns/'
      path: '/towns'
      fullPath: '/{-$lang}/towns/'
      preLoaderRoute: typeof Char123LangChar125TownsIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/system-map/': {
      id: '/{-$lang}/system-map/'
      path: '/system-map'
      fullPath: '/{-$lang}/system-map/'
      preLoaderRoute: typeof Char123LangChar125SystemMapIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/statistics/': {
      id: '/{-$lang}/statistics/'
      path: '/statistics'
      fullPath: '/{-$lang}/statistics/'
      preLoaderRoute: typeof Char123LangChar125StatisticsIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/stations/': {
      id: '/{-$lang}/stations/'
      path: '/stations'
      fullPath: '/{-$lang}/stations/'
      preLoaderRoute: typeof Char123LangChar125StationsIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/report/': {
      id: '/{-$lang}/report/'
      path: '/report'
      fullPath: '/{-$lang}/report/'
      preLoaderRoute: typeof Char123LangChar125ReportIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/lines/': {
      id: '/{-$lang}/lines/'
      path: '/lines'
      fullPath: '/{-$lang}/lines/'
      preLoaderRoute: typeof Char123LangChar125LinesIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/history/': {
      id: '/{-$lang}/history/'
      path: '/history'
      fullPath: '/{-$lang}/history/'
      preLoaderRoute: typeof Char123LangChar125HistoryIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/about/': {
      id: '/{-$lang}/about/'
      path: '/about'
      fullPath: '/{-$lang}/about/'
      preLoaderRoute: typeof Char123LangChar125AboutIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/stations/$stationId/index.md': {
      id: '/stations/$stationId/index.md'
      path: '/stations/$stationId/index.md'
      fullPath: '/stations/$stationId/index.md'
      preLoaderRoute: typeof StationsStationIdIndexDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators/$operatorId/index.md': {
      id: '/operators/$operatorId/index.md'
      path: '/operators/$operatorId/index.md'
      fullPath: '/operators/$operatorId/index.md'
      preLoaderRoute: typeof OperatorsOperatorIdIndexDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lines/$lineId/index.md': {
      id: '/lines/$lineId/index.md'
      path: '/lines/$lineId/index.md'
      fullPath: '/lines/$lineId/index.md'
      preLoaderRoute: typeof LinesLineIdIndexDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$issueId/index.md': {
      id: '/issues/$issueId/index.md'
      path: '/issues/$issueId/index.md'
      fullPath: '/issues/$issueId/index.md'
      preLoaderRoute: typeof IssuesIssueIdIndexDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ph/$': {
      id: '/api/ph/$'
      path: '/api/ph/$'
      fullPath: '/api/ph/$'
      preLoaderRoute: typeof ApiPhSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/towns/$townId/': {
      id: '/{-$lang}/towns/$townId/'
      path: '/towns/$townId'
      fullPath: '/{-$lang}/towns/$townId/'
      preLoaderRoute: typeof Char123LangChar125TownsTownIdIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/status/$lineId/': {
      id: '/{-$lang}/status/$lineId/'
      path: '/status/$lineId'
      fullPath: '/{-$lang}/status/$lineId/'
      preLoaderRoute: typeof Char123LangChar125StatusLineIdIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/stations/$stationId/': {
      id: '/{-$lang}/stations/$stationId/'
      path: '/stations/$stationId'
      fullPath: '/{-$lang}/stations/$stationId/'
      preLoaderRoute: typeof Char123LangChar125StationsStationIdIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/operators/$operatorId/': {
      id: '/{-$lang}/operators/$operatorId/'
      path: '/operators/$operatorId'
      fullPath: '/{-$lang}/operators/$operatorId/'
      preLoaderRoute: typeof Char123LangChar125OperatorsOperatorIdIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/lines/$lineId/': {
      id: '/{-$lang}/lines/$lineId/'
      path: '/lines/$lineId'
      fullPath: '/{-$lang}/lines/$lineId/'
      preLoaderRoute: typeof Char123LangChar125LinesLineIdIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/issues/$issueId/': {
      id: '/{-$lang}/issues/$issueId/'
      path: '/issues/$issueId'
      fullPath: '/{-$lang}/issues/$issueId/'
      preLoaderRoute: typeof Char123LangChar125IssuesIssueIdIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/history/$year/': {
      id: '/{-$lang}/history/$year/'
      path: '/history/$year'
      fullPath: '/{-$lang}/history/$year/'
      preLoaderRoute: typeof Char123LangChar125HistoryYearIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/internal/api/workflows/$workflowName': {
      id: '/internal/api/workflows/$workflowName'
      path: '/internal/api/workflows/$workflowName'
      fullPath: '/internal/api/workflows/$workflowName'
      preLoaderRoute: typeof InternalApiWorkflowsWorkflowNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/api/tasks/pull': {
      id: '/internal/api/tasks/pull'
      path: '/internal/api/tasks/pull'
      fullPath: '/internal/api/tasks/pull'
      preLoaderRoute: typeof InternalApiTasksPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/api/tasks/public-holidays': {
      id: '/internal/api/tasks/public-holidays'
      path: '/internal/api/tasks/public-holidays'
      fullPath: '/internal/api/tasks/public-holidays'
      preLoaderRoute: typeof InternalApiTasksPublicHolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/api/tasks/facts': {
      id: '/internal/api/tasks/facts'
      path: '/internal/api/tasks/facts'
      fullPath: '/internal/api/tasks/facts'
      preLoaderRoute: typeof InternalApiTasksFactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/api/tasks/crowd-report-dispatch': {
      id: '/internal/api/tasks/crowd-report-dispatch'
      path: '/internal/api/tasks/crowd-report-dispatch'
      fullPath: '/internal/api/tasks/crowd-report-dispatch'
      preLoaderRoute: typeof InternalApiTasksCrowdReportDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/history/page/$pageNum/': {
      id: '/{-$lang}/history/page/$pageNum/'
      path: '/history/page/$pageNum'
      fullPath: '/{-$lang}/history/page/$pageNum/'
      preLoaderRoute: typeof Char123LangChar125HistoryPagePageNumIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/history/$year/$month/': {
      id: '/{-$lang}/history/$year/$month/'
      path: '/history/$year/$month'
      fullPath: '/{-$lang}/history/$year/$month/'
      preLoaderRoute: typeof Char123LangChar125HistoryYearMonthIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/community-reports/$kind/$sourceId/': {
      id: '/{-$lang}/community-reports/$kind/$sourceId/'
      path: '/community-reports/$kind/$sourceId'
      fullPath: '/{-$lang}/community-reports/$kind/$sourceId/'
      preLoaderRoute: typeof Char123LangChar125CommunityReportsKindSourceIdIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
  }
}

interface Char123LangChar125RouteRouteChildren {
  Char123LangChar125SitemapDotxmlRoute: typeof Char123LangChar125SitemapDotxmlRoute
  Char123LangChar125IndexRoute: typeof Char123LangChar125IndexRoute
  Char123LangChar125AboutIndexRoute: typeof Char123LangChar125AboutIndexRoute
  Char123LangChar125HistoryIndexRoute: typeof Char123LangChar125HistoryIndexRoute
  Char123LangChar125LinesIndexRoute: typeof Char123LangChar125LinesIndexRoute
  Char123LangChar125ReportIndexRoute: typeof Char123LangChar125ReportIndexRoute
  Char123LangChar125StationsIndexRoute: typeof Char123LangChar125StationsIndexRoute
  Char123LangChar125StatisticsIndexRoute: typeof Char123LangChar125StatisticsIndexRoute
  Char123LangChar125SystemMapIndexRoute: typeof Char123LangChar125SystemMapIndexRoute
  Char123LangChar125TownsIndexRoute: typeof Char123LangChar125TownsIndexRoute
  Char123LangChar125HistoryYearIndexRoute: typeof Char123LangChar125HistoryYearIndexRoute
  Char123LangChar125IssuesIssueIdIndexRoute: typeof Char123LangChar125IssuesIssueIdIndexRoute
  Char123LangChar125LinesLineIdIndexRoute: typeof Char123LangChar125LinesLineIdIndexRoute
  Char123LangChar125OperatorsOperatorIdIndexRoute: typeof Char123LangChar125OperatorsOperatorIdIndexRoute
  Char123LangChar125StationsStationIdIndexRoute: typeof Char123LangChar125StationsStationIdIndexRoute
  Char123LangChar125StatusLineIdIndexRoute: typeof Char123LangChar125StatusLineIdIndexRoute
  Char123LangChar125TownsTownIdIndexRoute: typeof Char123LangChar125TownsTownIdIndexRoute
  Char123LangChar125CommunityReportsKindSourceIdIndexRoute: typeof Char123LangChar125CommunityReportsKindSourceIdIndexRoute
  Char123LangChar125HistoryYearMonthIndexRoute: typeof Char123LangChar125HistoryYearMonthIndexRoute
  Char123LangChar125HistoryPagePageNumIndexRoute: typeof Char123LangChar125HistoryPagePageNumIndexRoute
}

const Char123LangChar125RouteRouteChildren: Char123LangChar125RouteRouteChildren =
  {
    Char123LangChar125SitemapDotxmlRoute: Char123LangChar125SitemapDotxmlRoute,
    Char123LangChar125IndexRoute: Char123LangChar125IndexRoute,
    Char123LangChar125AboutIndexRoute: Char123LangChar125AboutIndexRoute,
    Char123LangChar125HistoryIndexRoute: Char123LangChar125HistoryIndexRoute,
    Char123LangChar125LinesIndexRoute: Char123LangChar125LinesIndexRoute,
    Char123LangChar125ReportIndexRoute: Char123LangChar125ReportIndexRoute,
    Char123LangChar125StationsIndexRoute: Char123LangChar125StationsIndexRoute,
    Char123LangChar125StatisticsIndexRoute:
      Char123LangChar125StatisticsIndexRoute,
    Char123LangChar125SystemMapIndexRoute:
      Char123LangChar125SystemMapIndexRoute,
    Char123LangChar125TownsIndexRoute: Char123LangChar125TownsIndexRoute,
    Char123LangChar125HistoryYearIndexRoute:
      Char123LangChar125HistoryYearIndexRoute,
    Char123LangChar125IssuesIssueIdIndexRoute:
      Char123LangChar125IssuesIssueIdIndexRoute,
    Char123LangChar125LinesLineIdIndexRoute:
      Char123LangChar125LinesLineIdIndexRoute,
    Char123LangChar125OperatorsOperatorIdIndexRoute:
      Char123LangChar125OperatorsOperatorIdIndexRoute,
    Char123LangChar125StationsStationIdIndexRoute:
      Char123LangChar125StationsStationIdIndexRoute,
    Char123LangChar125StatusLineIdIndexRoute:
      Char123LangChar125StatusLineIdIndexRoute,
    Char123LangChar125TownsTownIdIndexRoute:
      Char123LangChar125TownsTownIdIndexRoute,
    Char123LangChar125CommunityReportsKindSourceIdIndexRoute:
      Char123LangChar125CommunityReportsKindSourceIdIndexRoute,
    Char123LangChar125HistoryYearMonthIndexRoute:
      Char123LangChar125HistoryYearMonthIndexRoute,
    Char123LangChar125HistoryPagePageNumIndexRoute:
      Char123LangChar125HistoryPagePageNumIndexRoute,
  }

const Char123LangChar125RouteRouteWithChildren =
  Char123LangChar125RouteRoute._addFileChildren(
    Char123LangChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LangChar125RouteRoute: Char123LangChar125RouteRouteWithChildren,
  HealthzRoute: HealthzRoute,
  IndexDotmdRoute: IndexDotmdRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ApiIssuesDayRoute: ApiIssuesDayRoute,
  ApiReportsRoute: ApiReportsRoute,
  ApiSentryAnonymousUserRoute: ApiSentryAnonymousUserRoute,
  ApiPhSplatRoute: ApiPhSplatRoute,
  IssuesIssueIdIndexDotmdRoute: IssuesIssueIdIndexDotmdRoute,
  LinesLineIdIndexDotmdRoute: LinesLineIdIndexDotmdRoute,
  OperatorsOperatorIdIndexDotmdRoute: OperatorsOperatorIdIndexDotmdRoute,
  StationsStationIdIndexDotmdRoute: StationsStationIdIndexDotmdRoute,
  InternalApiTasksCrowdReportDispatchRoute:
    InternalApiTasksCrowdReportDispatchRoute,
  InternalApiTasksFactsRoute: InternalApiTasksFactsRoute,
  InternalApiTasksPublicHolidaysRoute: InternalApiTasksPublicHolidaysRoute,
  InternalApiTasksPullRoute: InternalApiTasksPullRoute,
  InternalApiWorkflowsWorkflowNameRoute: InternalApiWorkflowsWorkflowNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
