/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LangChar125RouteImport } from './routes/{-$lang}'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as IndexDotmdRouteImport } from './routes/index[.]md'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as Char123LangChar125IndexRouteImport } from './routes/{-$lang}/index'
import { Route as Char123LangChar125SystemMapRouteImport } from './routes/{-$lang}/system-map'
import { Route as Char123LangChar125SitemapDotxmlRouteImport } from './routes/{-$lang}/sitemap[.]xml'
import { Route as Char123LangChar125ReportRouteImport } from './routes/{-$lang}/report'
import { Route as Char123LangChar125AboutRouteImport } from './routes/{-$lang}/about'
import { Route as ApiReportsRouteImport } from './routes/api.reports'
import { Route as ApiIssuesDayRouteImport } from './routes/api.issues-day'
import { Route as Char123LangChar125StatisticsIndexRouteImport } from './routes/{-$lang}/statistics/index'
import { Route as Char123LangChar125HistoryIndexRouteImport } from './routes/{-$lang}/history/index'
import { Route as Char123LangChar125StatusLineIdRouteImport } from './routes/{-$lang}/status.$lineId'
import { Route as Char123LangChar125StationsStationIdRouteImport } from './routes/{-$lang}/stations/$stationId'
import { Route as StationsStationIdIndexDotmdRouteImport } from './routes/stations/$stationId/index[.]md'
import { Route as OperatorsOperatorIdIndexDotmdRouteImport } from './routes/operators/$operatorId/index[.]md'
import { Route as LinesLineIdIndexDotmdRouteImport } from './routes/lines/$lineId/index[.]md'
import { Route as IssuesIssueIdIndexDotmdRouteImport } from './routes/issues/$issueId/index[.]md'
import { Route as ApiPhSplatRouteImport } from './routes/api.ph.$'
import { Route as Char123LangChar125OperatorsOperatorIdIndexRouteImport } from './routes/{-$lang}/operators/$operatorId/index'
import { Route as Char123LangChar125LinesLineIdIndexRouteImport } from './routes/{-$lang}/lines/$lineId/index'
import { Route as Char123LangChar125IssuesIssueIdIndexRouteImport } from './routes/{-$lang}/issues/$issueId/index'
import { Route as Char123LangChar125HistoryYearIndexRouteImport } from './routes/{-$lang}/history/$year/index'
import { Route as Char123LangChar125HistoryPagePageNumRouteImport } from './routes/{-$lang}/history/page.$pageNum'
import { Route as Char123LangChar125HistoryYearMonthRouteImport } from './routes/{-$lang}/history/$year/$month'
import { Route as Char123LangChar125CommunityReportsKindSourceIdRouteImport } from './routes/{-$lang}/community-reports/$kind/$sourceId'
import { Route as InternalApiWorkflowsWorkflowNameRouteImport } from './routes/internal.api.workflows.$workflowName'
import { Route as InternalApiTasksPullRouteImport } from './routes/internal.api.tasks.pull'
import { Route as InternalApiTasksPublicHolidaysRouteImport } from './routes/internal.api.tasks.public-holidays'
import { Route as InternalApiTasksFactsRouteImport } from './routes/internal.api.tasks.facts'
import { Route as InternalApiTasksCrowdReportDispatchRouteImport } from './routes/internal.api.tasks.crowd-report-dispatch'

const Char123LangChar125Route = Char123LangChar125RouteImport.update({
  id: '/{-$lang}',
  path: '/{-$lang}',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexDotmdRoute = IndexDotmdRouteImport.update({
  id: '/index.md',
  path: '/index.md',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125IndexRoute = Char123LangChar125IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Char123LangChar125Route,
} as any)
const Char123LangChar125SystemMapRoute =
  Char123LangChar125SystemMapRouteImport.update({
    id: '/system-map',
    path: '/system-map',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125SitemapDotxmlRoute =
  Char123LangChar125SitemapDotxmlRouteImport.update({
    id: '/sitemap.xml',
    path: '/sitemap.xml',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125ReportRoute =
  Char123LangChar125ReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125AboutRoute = Char123LangChar125AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => Char123LangChar125Route,
} as any)
const ApiReportsRoute = ApiReportsRouteImport.update({
  id: '/api/reports',
  path: '/api/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIssuesDayRoute = ApiIssuesDayRouteImport.update({
  id: '/api/issues-day',
  path: '/api/issues-day',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125StatisticsIndexRoute =
  Char123LangChar125StatisticsIndexRouteImport.update({
    id: '/statistics/',
    path: '/statistics/',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125HistoryIndexRoute =
  Char123LangChar125HistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125StatusLineIdRoute =
  Char123LangChar125StatusLineIdRouteImport.update({
    id: '/status/$lineId',
    path: '/status/$lineId',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125StationsStationIdRoute =
  Char123LangChar125StationsStationIdRouteImport.update({
    id: '/stations/$stationId',
    path: '/stations/$stationId',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const StationsStationIdIndexDotmdRoute =
  StationsStationIdIndexDotmdRouteImport.update({
    id: '/stations/$stationId/index.md',
    path: '/stations/$stationId/index.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperatorsOperatorIdIndexDotmdRoute =
  OperatorsOperatorIdIndexDotmdRouteImport.update({
    id: '/operators/$operatorId/index.md',
    path: '/operators/$operatorId/index.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const LinesLineIdIndexDotmdRoute = LinesLineIdIndexDotmdRouteImport.update({
  id: '/lines/$lineId/index.md',
  path: '/lines/$lineId/index.md',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIssueIdIndexDotmdRoute = IssuesIssueIdIndexDotmdRouteImport.update({
  id: '/issues/$issueId/index.md',
  path: '/issues/$issueId/index.md',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhSplatRoute = ApiPhSplatRouteImport.update({
  id: '/api/ph/$',
  path: '/api/ph/$',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125OperatorsOperatorIdIndexRoute =
  Char123LangChar125OperatorsOperatorIdIndexRouteImport.update({
    id: '/operators/$operatorId/',
    path: '/operators/$operatorId/',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125LinesLineIdIndexRoute =
  Char123LangChar125LinesLineIdIndexRouteImport.update({
    id: '/lines/$lineId/',
    path: '/lines/$lineId/',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125IssuesIssueIdIndexRoute =
  Char123LangChar125IssuesIssueIdIndexRouteImport.update({
    id: '/issues/$issueId/',
    path: '/issues/$issueId/',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125HistoryYearIndexRoute =
  Char123LangChar125HistoryYearIndexRouteImport.update({
    id: '/history/$year/',
    path: '/history/$year/',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125HistoryPagePageNumRoute =
  Char123LangChar125HistoryPagePageNumRouteImport.update({
    id: '/history/page/$pageNum',
    path: '/history/page/$pageNum',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125HistoryYearMonthRoute =
  Char123LangChar125HistoryYearMonthRouteImport.update({
    id: '/history/$year/$month',
    path: '/history/$year/$month',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125CommunityReportsKindSourceIdRoute =
  Char123LangChar125CommunityReportsKindSourceIdRouteImport.update({
    id: '/community-reports/$kind/$sourceId',
    path: '/community-reports/$kind/$sourceId',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const InternalApiWorkflowsWorkflowNameRoute =
  InternalApiWorkflowsWorkflowNameRouteImport.update({
    id: '/internal/api/workflows/$workflowName',
    path: '/internal/api/workflows/$workflowName',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalApiTasksPullRoute = InternalApiTasksPullRouteImport.update({
  id: '/internal/api/tasks/pull',
  path: '/internal/api/tasks/pull',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalApiTasksPublicHolidaysRoute =
  InternalApiTasksPublicHolidaysRouteImport.update({
    id: '/internal/api/tasks/public-holidays',
    path: '/internal/api/tasks/public-holidays',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalApiTasksFactsRoute = InternalApiTasksFactsRouteImport.update({
  id: '/internal/api/tasks/facts',
  path: '/internal/api/tasks/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalApiTasksCrowdReportDispatchRoute =
  InternalApiTasksCrowdReportDispatchRouteImport.update({
    id: '/internal/api/tasks/crowd-report-dispatch',
    path: '/internal/api/tasks/crowd-report-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/healthz': typeof HealthzRoute
  '/index.md': typeof IndexDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/{-$lang}': typeof Char123LangChar125RouteWithChildren
  '/api/issues-day': typeof ApiIssuesDayRoute
  '/api/reports': typeof ApiReportsRoute
  '/{-$lang}/about': typeof Char123LangChar125AboutRoute
  '/{-$lang}/report': typeof Char123LangChar125ReportRoute
  '/{-$lang}/sitemap.xml': typeof Char123LangChar125SitemapDotxmlRoute
  '/{-$lang}/system-map': typeof Char123LangChar125SystemMapRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/api/ph/$': typeof ApiPhSplatRoute
  '/issues/$issueId/index.md': typeof IssuesIssueIdIndexDotmdRoute
  '/lines/$lineId/index.md': typeof LinesLineIdIndexDotmdRoute
  '/operators/$operatorId/index.md': typeof OperatorsOperatorIdIndexDotmdRoute
  '/stations/$stationId/index.md': typeof StationsStationIdIndexDotmdRoute
  '/{-$lang}/stations/$stationId': typeof Char123LangChar125StationsStationIdRoute
  '/{-$lang}/status/$lineId': typeof Char123LangChar125StatusLineIdRoute
  '/{-$lang}/history/': typeof Char123LangChar125HistoryIndexRoute
  '/{-$lang}/statistics/': typeof Char123LangChar125StatisticsIndexRoute
  '/internal/api/tasks/crowd-report-dispatch': typeof InternalApiTasksCrowdReportDispatchRoute
  '/internal/api/tasks/facts': typeof InternalApiTasksFactsRoute
  '/internal/api/tasks/public-holidays': typeof InternalApiTasksPublicHolidaysRoute
  '/internal/api/tasks/pull': typeof InternalApiTasksPullRoute
  '/internal/api/workflows/$workflowName': typeof InternalApiWorkflowsWorkflowNameRoute
  '/{-$lang}/community-reports/$kind/$sourceId': typeof Char123LangChar125CommunityReportsKindSourceIdRoute
  '/{-$lang}/history/$year/$month': typeof Char123LangChar125HistoryYearMonthRoute
  '/{-$lang}/history/page/$pageNum': typeof Char123LangChar125HistoryPagePageNumRoute
  '/{-$lang}/history/$year/': typeof Char123LangChar125HistoryYearIndexRoute
  '/{-$lang}/issues/$issueId/': typeof Char123LangChar125IssuesIssueIdIndexRoute
  '/{-$lang}/lines/$lineId/': typeof Char123LangChar125LinesLineIdIndexRoute
  '/{-$lang}/operators/$operatorId/': typeof Char123LangChar125OperatorsOperatorIdIndexRoute
}
export interface FileRoutesByTo {
  '/healthz': typeof HealthzRoute
  '/index.md': typeof IndexDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/issues-day': typeof ApiIssuesDayRoute
  '/api/reports': typeof ApiReportsRoute
  '/{-$lang}/about': typeof Char123LangChar125AboutRoute
  '/{-$lang}/report': typeof Char123LangChar125ReportRoute
  '/{-$lang}/sitemap.xml': typeof Char123LangChar125SitemapDotxmlRoute
  '/{-$lang}/system-map': typeof Char123LangChar125SystemMapRoute
  '/{-$lang}': typeof Char123LangChar125IndexRoute
  '/api/ph/$': typeof ApiPhSplatRoute
  '/issues/$issueId/index.md': typeof IssuesIssueIdIndexDotmdRoute
  '/lines/$lineId/index.md': typeof LinesLineIdIndexDotmdRoute
  '/operators/$operatorId/index.md': typeof OperatorsOperatorIdIndexDotmdRoute
  '/stations/$stationId/index.md': typeof StationsStationIdIndexDotmdRoute
  '/{-$lang}/stations/$stationId': typeof Char123LangChar125StationsStationIdRoute
  '/{-$lang}/status/$lineId': typeof Char123LangChar125StatusLineIdRoute
  '/{-$lang}/history': typeof Char123LangChar125HistoryIndexRoute
  '/{-$lang}/statistics': typeof Char123LangChar125StatisticsIndexRoute
  '/internal/api/tasks/crowd-report-dispatch': typeof InternalApiTasksCrowdReportDispatchRoute
  '/internal/api/tasks/facts': typeof InternalApiTasksFactsRoute
  '/internal/api/tasks/public-holidays': typeof InternalApiTasksPublicHolidaysRoute
  '/internal/api/tasks/pull': typeof InternalApiTasksPullRoute
  '/internal/api/workflows/$workflowName': typeof InternalApiWorkflowsWorkflowNameRoute
  '/{-$lang}/community-reports/$kind/$sourceId': typeof Char123LangChar125CommunityReportsKindSourceIdRoute
  '/{-$lang}/history/$year/$month': typeof Char123LangChar125HistoryYearMonthRoute
  '/{-$lang}/history/page/$pageNum': typeof Char123LangChar125HistoryPagePageNumRoute
  '/{-$lang}/history/$year': typeof Char123LangChar125HistoryYearIndexRoute
  '/{-$lang}/issues/$issueId': typeof Char123LangChar125IssuesIssueIdIndexRoute
  '/{-$lang}/lines/$lineId': typeof Char123LangChar125LinesLineIdIndexRoute
  '/{-$lang}/operators/$operatorId': typeof Char123LangChar125OperatorsOperatorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/healthz': typeof HealthzRoute
  '/index.md': typeof IndexDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/{-$lang}': typeof Char123LangChar125RouteWithChildren
  '/api/issues-day': typeof ApiIssuesDayRoute
  '/api/reports': typeof ApiReportsRoute
  '/{-$lang}/about': typeof Char123LangChar125AboutRoute
  '/{-$lang}/report': typeof Char123LangChar125ReportRoute
  '/{-$lang}/sitemap.xml': typeof Char123LangChar125SitemapDotxmlRoute
  '/{-$lang}/system-map': typeof Char123LangChar125SystemMapRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/api/ph/$': typeof ApiPhSplatRoute
  '/issues/$issueId/index.md': typeof IssuesIssueIdIndexDotmdRoute
  '/lines/$lineId/index.md': typeof LinesLineIdIndexDotmdRoute
  '/operators/$operatorId/index.md': typeof OperatorsOperatorIdIndexDotmdRoute
  '/stations/$stationId/index.md': typeof StationsStationIdIndexDotmdRoute
  '/{-$lang}/stations/$stationId': typeof Char123LangChar125StationsStationIdRoute
  '/{-$lang}/status/$lineId': typeof Char123LangChar125StatusLineIdRoute
  '/{-$lang}/history/': typeof Char123LangChar125HistoryIndexRoute
  '/{-$lang}/statistics/': typeof Char123LangChar125StatisticsIndexRoute
  '/internal/api/tasks/crowd-report-dispatch': typeof InternalApiTasksCrowdReportDispatchRoute
  '/internal/api/tasks/facts': typeof InternalApiTasksFactsRoute
  '/internal/api/tasks/public-holidays': typeof InternalApiTasksPublicHolidaysRoute
  '/internal/api/tasks/pull': typeof InternalApiTasksPullRoute
  '/internal/api/workflows/$workflowName': typeof InternalApiWorkflowsWorkflowNameRoute
  '/{-$lang}/community-reports/$kind/$sourceId': typeof Char123LangChar125CommunityReportsKindSourceIdRoute
  '/{-$lang}/history/$year/$month': typeof Char123LangChar125HistoryYearMonthRoute
  '/{-$lang}/history/page/$pageNum': typeof Char123LangChar125HistoryPagePageNumRoute
  '/{-$lang}/history/$year/': typeof Char123LangChar125HistoryYearIndexRoute
  '/{-$lang}/issues/$issueId/': typeof Char123LangChar125IssuesIssueIdIndexRoute
  '/{-$lang}/lines/$lineId/': typeof Char123LangChar125LinesLineIdIndexRoute
  '/{-$lang}/operators/$operatorId/': typeof Char123LangChar125OperatorsOperatorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/healthz'
    | '/index.md'
    | '/llms.txt'
    | '/{-$lang}'
    | '/api/issues-day'
    | '/api/reports'
    | '/{-$lang}/about'
    | '/{-$lang}/report'
    | '/{-$lang}/sitemap.xml'
    | '/{-$lang}/system-map'
    | '/{-$lang}/'
    | '/api/ph/$'
    | '/issues/$issueId/index.md'
    | '/lines/$lineId/index.md'
    | '/operators/$operatorId/index.md'
    | '/stations/$stationId/index.md'
    | '/{-$lang}/stations/$stationId'
    | '/{-$lang}/status/$lineId'
    | '/{-$lang}/history/'
    | '/{-$lang}/statistics/'
    | '/internal/api/tasks/crowd-report-dispatch'
    | '/internal/api/tasks/facts'
    | '/internal/api/tasks/public-holidays'
    | '/internal/api/tasks/pull'
    | '/internal/api/workflows/$workflowName'
    | '/{-$lang}/community-reports/$kind/$sourceId'
    | '/{-$lang}/history/$year/$month'
    | '/{-$lang}/history/page/$pageNum'
    | '/{-$lang}/history/$year/'
    | '/{-$lang}/issues/$issueId/'
    | '/{-$lang}/lines/$lineId/'
    | '/{-$lang}/operators/$operatorId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/healthz'
    | '/index.md'
    | '/llms.txt'
    | '/api/issues-day'
    | '/api/reports'
    | '/{-$lang}/about'
    | '/{-$lang}/report'
    | '/{-$lang}/sitemap.xml'
    | '/{-$lang}/system-map'
    | '/{-$lang}'
    | '/api/ph/$'
    | '/issues/$issueId/index.md'
    | '/lines/$lineId/index.md'
    | '/operators/$operatorId/index.md'
    | '/stations/$stationId/index.md'
    | '/{-$lang}/stations/$stationId'
    | '/{-$lang}/status/$lineId'
    | '/{-$lang}/history'
    | '/{-$lang}/statistics'
    | '/internal/api/tasks/crowd-report-dispatch'
    | '/internal/api/tasks/facts'
    | '/internal/api/tasks/public-holidays'
    | '/internal/api/tasks/pull'
    | '/internal/api/workflows/$workflowName'
    | '/{-$lang}/community-reports/$kind/$sourceId'
    | '/{-$lang}/history/$year/$month'
    | '/{-$lang}/history/page/$pageNum'
    | '/{-$lang}/history/$year'
    | '/{-$lang}/issues/$issueId'
    | '/{-$lang}/lines/$lineId'
    | '/{-$lang}/operators/$operatorId'
  id:
    | '__root__'
    | '/healthz'
    | '/index.md'
    | '/llms.txt'
    | '/{-$lang}'
    | '/api/issues-day'
    | '/api/reports'
    | '/{-$lang}/about'
    | '/{-$lang}/report'
    | '/{-$lang}/sitemap.xml'
    | '/{-$lang}/system-map'
    | '/{-$lang}/'
    | '/api/ph/$'
    | '/issues/$issueId/index.md'
    | '/lines/$lineId/index.md'
    | '/operators/$operatorId/index.md'
    | '/stations/$stationId/index.md'
    | '/{-$lang}/stations/$stationId'
    | '/{-$lang}/status/$lineId'
    | '/{-$lang}/history/'
    | '/{-$lang}/statistics/'
    | '/internal/api/tasks/crowd-report-dispatch'
    | '/internal/api/tasks/facts'
    | '/internal/api/tasks/public-holidays'
    | '/internal/api/tasks/pull'
    | '/internal/api/workflows/$workflowName'
    | '/{-$lang}/community-reports/$kind/$sourceId'
    | '/{-$lang}/history/$year/$month'
    | '/{-$lang}/history/page/$pageNum'
    | '/{-$lang}/history/$year/'
    | '/{-$lang}/issues/$issueId/'
    | '/{-$lang}/lines/$lineId/'
    | '/{-$lang}/operators/$operatorId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HealthzRoute: typeof HealthzRoute
  IndexDotmdRoute: typeof IndexDotmdRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  Char123LangChar125Route: typeof Char123LangChar125RouteWithChildren
  ApiIssuesDayRoute: typeof ApiIssuesDayRoute
  ApiReportsRoute: typeof ApiReportsRoute
  ApiPhSplatRoute: typeof ApiPhSplatRoute
  IssuesIssueIdIndexDotmdRoute: typeof IssuesIssueIdIndexDotmdRoute
  LinesLineIdIndexDotmdRoute: typeof LinesLineIdIndexDotmdRoute
  OperatorsOperatorIdIndexDotmdRoute: typeof OperatorsOperatorIdIndexDotmdRoute
  StationsStationIdIndexDotmdRoute: typeof StationsStationIdIndexDotmdRoute
  InternalApiTasksCrowdReportDispatchRoute: typeof InternalApiTasksCrowdReportDispatchRoute
  InternalApiTasksFactsRoute: typeof InternalApiTasksFactsRoute
  InternalApiTasksPublicHolidaysRoute: typeof InternalApiTasksPublicHolidaysRoute
  InternalApiTasksPullRoute: typeof InternalApiTasksPullRoute
  InternalApiWorkflowsWorkflowNameRoute: typeof InternalApiWorkflowsWorkflowNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$lang}': {
      id: '/{-$lang}'
      path: '/{-$lang}'
      fullPath: '/{-$lang}'
      preLoaderRoute: typeof Char123LangChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index.md': {
      id: '/index.md'
      path: '/index.md'
      fullPath: '/index.md'
      preLoaderRoute: typeof IndexDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/': {
      id: '/{-$lang}/'
      path: '/'
      fullPath: '/{-$lang}/'
      preLoaderRoute: typeof Char123LangChar125IndexRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/system-map': {
      id: '/{-$lang}/system-map'
      path: '/system-map'
      fullPath: '/{-$lang}/system-map'
      preLoaderRoute: typeof Char123LangChar125SystemMapRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/sitemap.xml': {
      id: '/{-$lang}/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/{-$lang}/sitemap.xml'
      preLoaderRoute: typeof Char123LangChar125SitemapDotxmlRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/report': {
      id: '/{-$lang}/report'
      path: '/report'
      fullPath: '/{-$lang}/report'
      preLoaderRoute: typeof Char123LangChar125ReportRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/about': {
      id: '/{-$lang}/about'
      path: '/about'
      fullPath: '/{-$lang}/about'
      preLoaderRoute: typeof Char123LangChar125AboutRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/api/reports': {
      id: '/api/reports'
      path: '/api/reports'
      fullPath: '/api/reports'
      preLoaderRoute: typeof ApiReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/issues-day': {
      id: '/api/issues-day'
      path: '/api/issues-day'
      fullPath: '/api/issues-day'
      preLoaderRoute: typeof ApiIssuesDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/statistics/': {
      id: '/{-$lang}/statistics/'
      path: '/statistics'
      fullPath: '/{-$lang}/statistics/'
      preLoaderRoute: typeof Char123LangChar125StatisticsIndexRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/history/': {
      id: '/{-$lang}/history/'
      path: '/history'
      fullPath: '/{-$lang}/history/'
      preLoaderRoute: typeof Char123LangChar125HistoryIndexRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/status/$lineId': {
      id: '/{-$lang}/status/$lineId'
      path: '/status/$lineId'
      fullPath: '/{-$lang}/status/$lineId'
      preLoaderRoute: typeof Char123LangChar125StatusLineIdRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/stations/$stationId': {
      id: '/{-$lang}/stations/$stationId'
      path: '/stations/$stationId'
      fullPath: '/{-$lang}/stations/$stationId'
      preLoaderRoute: typeof Char123LangChar125StationsStationIdRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/stations/$stationId/index.md': {
      id: '/stations/$stationId/index.md'
      path: '/stations/$stationId/index.md'
      fullPath: '/stations/$stationId/index.md'
      preLoaderRoute: typeof StationsStationIdIndexDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators/$operatorId/index.md': {
      id: '/operators/$operatorId/index.md'
      path: '/operators/$operatorId/index.md'
      fullPath: '/operators/$operatorId/index.md'
      preLoaderRoute: typeof OperatorsOperatorIdIndexDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lines/$lineId/index.md': {
      id: '/lines/$lineId/index.md'
      path: '/lines/$lineId/index.md'
      fullPath: '/lines/$lineId/index.md'
      preLoaderRoute: typeof LinesLineIdIndexDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$issueId/index.md': {
      id: '/issues/$issueId/index.md'
      path: '/issues/$issueId/index.md'
      fullPath: '/issues/$issueId/index.md'
      preLoaderRoute: typeof IssuesIssueIdIndexDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ph/$': {
      id: '/api/ph/$'
      path: '/api/ph/$'
      fullPath: '/api/ph/$'
      preLoaderRoute: typeof ApiPhSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/operators/$operatorId/': {
      id: '/{-$lang}/operators/$operatorId/'
      path: '/operators/$operatorId'
      fullPath: '/{-$lang}/operators/$operatorId/'
      preLoaderRoute: typeof Char123LangChar125OperatorsOperatorIdIndexRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/lines/$lineId/': {
      id: '/{-$lang}/lines/$lineId/'
      path: '/lines/$lineId'
      fullPath: '/{-$lang}/lines/$lineId/'
      preLoaderRoute: typeof Char123LangChar125LinesLineIdIndexRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/issues/$issueId/': {
      id: '/{-$lang}/issues/$issueId/'
      path: '/issues/$issueId'
      fullPath: '/{-$lang}/issues/$issueId/'
      preLoaderRoute: typeof Char123LangChar125IssuesIssueIdIndexRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/history/$year/': {
      id: '/{-$lang}/history/$year/'
      path: '/history/$year'
      fullPath: '/{-$lang}/history/$year/'
      preLoaderRoute: typeof Char123LangChar125HistoryYearIndexRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/history/page/$pageNum': {
      id: '/{-$lang}/history/page/$pageNum'
      path: '/history/page/$pageNum'
      fullPath: '/{-$lang}/history/page/$pageNum'
      preLoaderRoute: typeof Char123LangChar125HistoryPagePageNumRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/history/$year/$month': {
      id: '/{-$lang}/history/$year/$month'
      path: '/history/$year/$month'
      fullPath: '/{-$lang}/history/$year/$month'
      preLoaderRoute: typeof Char123LangChar125HistoryYearMonthRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/community-reports/$kind/$sourceId': {
      id: '/{-$lang}/community-reports/$kind/$sourceId'
      path: '/community-reports/$kind/$sourceId'
      fullPath: '/{-$lang}/community-reports/$kind/$sourceId'
      preLoaderRoute: typeof Char123LangChar125CommunityReportsKindSourceIdRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/internal/api/workflows/$workflowName': {
      id: '/internal/api/workflows/$workflowName'
      path: '/internal/api/workflows/$workflowName'
      fullPath: '/internal/api/workflows/$workflowName'
      preLoaderRoute: typeof InternalApiWorkflowsWorkflowNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/api/tasks/pull': {
      id: '/internal/api/tasks/pull'
      path: '/internal/api/tasks/pull'
      fullPath: '/internal/api/tasks/pull'
      preLoaderRoute: typeof InternalApiTasksPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/api/tasks/public-holidays': {
      id: '/internal/api/tasks/public-holidays'
      path: '/internal/api/tasks/public-holidays'
      fullPath: '/internal/api/tasks/public-holidays'
      preLoaderRoute: typeof InternalApiTasksPublicHolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/api/tasks/facts': {
      id: '/internal/api/tasks/facts'
      path: '/internal/api/tasks/facts'
      fullPath: '/internal/api/tasks/facts'
      preLoaderRoute: typeof InternalApiTasksFactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/api/tasks/crowd-report-dispatch': {
      id: '/internal/api/tasks/crowd-report-dispatch'
      path: '/internal/api/tasks/crowd-report-dispatch'
      fullPath: '/internal/api/tasks/crowd-report-dispatch'
      preLoaderRoute: typeof InternalApiTasksCrowdReportDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char123LangChar125RouteChildren {
  Char123LangChar125AboutRoute: typeof Char123LangChar125AboutRoute
  Char123LangChar125ReportRoute: typeof Char123LangChar125ReportRoute
  Char123LangChar125SitemapDotxmlRoute: typeof Char123LangChar125SitemapDotxmlRoute
  Char123LangChar125SystemMapRoute: typeof Char123LangChar125SystemMapRoute
  Char123LangChar125IndexRoute: typeof Char123LangChar125IndexRoute
  Char123LangChar125StationsStationIdRoute: typeof Char123LangChar125StationsStationIdRoute
  Char123LangChar125StatusLineIdRoute: typeof Char123LangChar125StatusLineIdRoute
  Char123LangChar125HistoryIndexRoute: typeof Char123LangChar125HistoryIndexRoute
  Char123LangChar125StatisticsIndexRoute: typeof Char123LangChar125StatisticsIndexRoute
  Char123LangChar125CommunityReportsKindSourceIdRoute: typeof Char123LangChar125CommunityReportsKindSourceIdRoute
  Char123LangChar125HistoryYearMonthRoute: typeof Char123LangChar125HistoryYearMonthRoute
  Char123LangChar125HistoryPagePageNumRoute: typeof Char123LangChar125HistoryPagePageNumRoute
  Char123LangChar125HistoryYearIndexRoute: typeof Char123LangChar125HistoryYearIndexRoute
  Char123LangChar125IssuesIssueIdIndexRoute: typeof Char123LangChar125IssuesIssueIdIndexRoute
  Char123LangChar125LinesLineIdIndexRoute: typeof Char123LangChar125LinesLineIdIndexRoute
  Char123LangChar125OperatorsOperatorIdIndexRoute: typeof Char123LangChar125OperatorsOperatorIdIndexRoute
}

const Char123LangChar125RouteChildren: Char123LangChar125RouteChildren = {
  Char123LangChar125AboutRoute: Char123LangChar125AboutRoute,
  Char123LangChar125ReportRoute: Char123LangChar125ReportRoute,
  Char123LangChar125SitemapDotxmlRoute: Char123LangChar125SitemapDotxmlRoute,
  Char123LangChar125SystemMapRoute: Char123LangChar125SystemMapRoute,
  Char123LangChar125IndexRoute: Char123LangChar125IndexRoute,
  Char123LangChar125StationsStationIdRoute:
    Char123LangChar125StationsStationIdRoute,
  Char123LangChar125StatusLineIdRoute: Char123LangChar125StatusLineIdRoute,
  Char123LangChar125HistoryIndexRoute: Char123LangChar125HistoryIndexRoute,
  Char123LangChar125StatisticsIndexRoute:
    Char123LangChar125StatisticsIndexRoute,
  Char123LangChar125CommunityReportsKindSourceIdRoute:
    Char123LangChar125CommunityReportsKindSourceIdRoute,
  Char123LangChar125HistoryYearMonthRoute:
    Char123LangChar125HistoryYearMonthRoute,
  Char123LangChar125HistoryPagePageNumRoute:
    Char123LangChar125HistoryPagePageNumRoute,
  Char123LangChar125HistoryYearIndexRoute:
    Char123LangChar125HistoryYearIndexRoute,
  Char123LangChar125IssuesIssueIdIndexRoute:
    Char123LangChar125IssuesIssueIdIndexRoute,
  Char123LangChar125LinesLineIdIndexRoute:
    Char123LangChar125LinesLineIdIndexRoute,
  Char123LangChar125OperatorsOperatorIdIndexRoute:
    Char123LangChar125OperatorsOperatorIdIndexRoute,
}

const Char123LangChar125RouteWithChildren =
  Char123LangChar125Route._addFileChildren(Char123LangChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HealthzRoute: HealthzRoute,
  IndexDotmdRoute: IndexDotmdRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  Char123LangChar125Route: Char123LangChar125RouteWithChildren,
  ApiIssuesDayRoute: ApiIssuesDayRoute,
  ApiReportsRoute: ApiReportsRoute,
  ApiPhSplatRoute: ApiPhSplatRoute,
  IssuesIssueIdIndexDotmdRoute: IssuesIssueIdIndexDotmdRoute,
  LinesLineIdIndexDotmdRoute: LinesLineIdIndexDotmdRoute,
  OperatorsOperatorIdIndexDotmdRoute: OperatorsOperatorIdIndexDotmdRoute,
  StationsStationIdIndexDotmdRoute: StationsStationIdIndexDotmdRoute,
  InternalApiTasksCrowdReportDispatchRoute:
    InternalApiTasksCrowdReportDispatchRoute,
  InternalApiTasksFactsRoute: InternalApiTasksFactsRoute,
  InternalApiTasksPublicHolidaysRoute: InternalApiTasksPublicHolidaysRoute,
  InternalApiTasksPullRoute: InternalApiTasksPullRoute,
  InternalApiWorkflowsWorkflowNameRoute: InternalApiWorkflowsWorkflowNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
