name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-production
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
      - run: |-
          npm ci
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to production
        run: |-
          flyctl deploy --local-only -a mrtdown-site --env "TIER=production" \
            --build-arg SENTRY_ORG=${{ secrets.SENTRY_ORG }} \
            --build-arg SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }} \
            --build-arg SENTRY_RELEASE=${{ github.sha }} \
            --build-arg SENTRY_DSN=${{ secrets.SENTRY_DSN }} \
            --build-secret SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} \
            --build-arg VITE_PUBLIC_POSTHOG_KEY=${{ secrets.VITE_PUBLIC_POSTHOG_KEY }} \
            --build-arg VITE_PUBLIC_POSTHOG_HOST=${{ secrets.VITE_PUBLIC_POSTHOG_HOST }} \
            --image-label=${{ github.sha }}
        env:
          GIT_SHA: ${{ github.sha }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}